/**
 * Simularemos un .env con esta constante
 */
export const MICROSERVICE_PORTS = {
  AUTH_MICROSERVICE: 3001,
  USERS_MICROSERVICE: 3002,
  PROJECTS_MICROSERVICE: 3003,
  TASKS_MICROSERVICE: 3004,
};
