/**
 * Simulacion de un .env con esta constante
 */
export const MICROSERVICE_PORTS = {
  API_GATEAWAY: 8000,
  AUTH_MICROSERVICE: 8001,
  USERS_MICROSERVICE: 8002,
  PROJECTS_MICROSERVICE: 8003,
  TASKS_MICROSERVICE: 8004,
};
