/**
 * Simulacion de un .env con esta constante
 */
export const MICROSERVICE_PORTS = {
  AUTH_MICROSERVICE: 63001,
  USERS_MICROSERVICE: 6002,
  PROJECTS_MICROSERVICE: 6003,
  TASKS_MICROSERVICE: 6004,
};
