services:
  app:
    build: 
      context: .
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
      - "8004:8004"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development